### PR TITLE
Call Dispose methods. r=garndt

### PR DESCRIPTION
**Pull request by walac**
Call TaskPlugin and ResultSet Dispose methods after task is finished.

### CODE REVIEW

**Comment by gregarndt** [comment]
If travis is happy then I'm happy.

**Comment by walac** [comment]
Travis is not happy, but seems unrelated to the patch. @petemoore ?

**Comment by gregarndt** [comment]
I don't think it was related to this patch or what pmoore changed.  I think it was just travis being wonky.  I retriggered the builds and it looks fine.

**Comment by walac** [comment]
Poor travis. Anyway, merged.

**Pull request merged**
