### PR TITLE
The credentials service returns {credentials: ..}, so expect that

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by djmitche** [comment]
Once this is merged, let's release a new version (0.1.0, since there have been a LOT of breaking changes since 0.0.13?) and I'll deploy that and test it on the in-house linux.

**Comment by djmitche** [comment]
Looks like that travis failure is an intermittent.

**Comment by jonasfj** [comment]
If it's the osx thing I have a patch for it on one of the other PRs I have
in the pipeline...

Den 21. apr. 2017 12.06 PM skrev "Dustin J. Mitchell" <
notifications@github.com>:

**Comment by djmitche** [comment]
it is, yes

**Comment by jonasfj** [comment]
Why 1.0? already... I have quite a few changes in the pipeline... Just make it `0.1.0` that'll feel like a big step up from `0.0.13`.. :)

**Comment by djmitche** [comment]
That's what I said :)

**Comment by jonasfj** [comment]
Lol, I read it wrong...

**Pull request merged**
