### PR TITLE
godep update

### PR DESCRIPTION
**Pull request by jonasfj**
@petemoore , this took forever to figure out... but `godep update ./...` is the right thing... `godep save ./...` only adds new dependencies...

### CODE REVIEW

**Comment by jonasfj** [comment]
Okay, now it makes more sense... `godep save ./...` will just add deps that aren't already there... and save existing dependencies to what the godep file says...

`godep update ./...` will update the godep file to latest version of everything... based on what is currently checked out...

**Comment by petemoore** [comment]
Thanks for this Jonas! That explains a lot. =)

It sounds like we should have an explanation of both commands (since sometimes we'll add new dependencies) - can you document both, rather than removing the details about `godep save`?

**Comment by jonasfj** [comment]
@petemoore, better?

**Comment by petemoore** [comment]
> @petemoore, better?

beautiful! :+1:

**Pull request merged**
